# Generated by Django 5.1.3 on 2024-11-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Accessories', 'ACCESSORIES'), ('Peripherals', 'PERIPHERALS'), ('PC Components', 'PC COMPONENTS')], max_length=15, null=True),
        ),
    ]
